require('./js/app.js');
require('./js/conf-http.js');
require('./js/fact-locations.js');
require('./js/conf-uirouter.js');
require('./js/ctrl-app.js');
require('./view/view1/view1.js');
require('./view/view2/view2.js');
require('./scss/app.scss');
require('jquery');
